Fix flags when running without TTY
sqitchers/docker-sqitch pull request #45
Opened 2022-08-07 02:41 UTC by ewie

Make sure the container can be run without a TTY, e.g. deploying changes when testing in a CI pipeline.

The following pipes and redirects are now possible:

```console
$        ./docker-sqitch.sh
$        ./docker-sqitch.sh < file
$        ./docker-sqitch.sh < file | less
$        ./docker-sqitch.sh        | less
$ echo | ./docker-sqitch.sh        | less
$ echo | ./docker-sqitch.sh
$ echo | ./docker-sqitch.sh > file
$        ./docker-sqitch.sh > file
```

2022-08-07 02:54 UTC, ewie commented
I have no idea how to apply this to `docker-sqitch.bat` as well, let alone test it.

2022-08-07 18:30 UTC, theory requested changes
Looks like it includes`--interactive` either way; should it be changed to just add `--tty` when there is one?

2022-08-07 19:44 UTC, ewie commented
> Looks like it includes`--interactive` either way; should it be changed to just add `--tty` when there is one?

The key is the omitted `else` clause. In that case neither `--interactive` nor `--tty` applies and they default to `false` when not specified in `docker run`.

I can change it to this canonical form to make the logic less obscure:

```bash
if [ -t 0 ] && [ -t 1 ]; then
    passopt+=(--interactive=true --tty=true)
elif [ ! -t 0 ]; then
    passopt+=(--interactive=true --tty=false)
else
    passopt+=(--interactive=false --tty=false)
fi
```

2022-08-08 01:28 UTC, theory commented
OH 🤦🏻 no I didn't read it closely enough, totally overlooked the `elif` expression. It's good like this, thanks!

2022-08-08 01:28 UTC, theory approved these changes

2022-08-08 01:34 UTC, merged